In [2]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [4]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [7]:
a=np.array([1,2,3,4,5])
np.full_like(a,4)

array([4, 4, 4, 4, 4])

建立随机数组

In [9]:
np.random.rand(4,2,3)

array([[[0.8928758 , 0.22264264, 0.34409237],
        [0.42603454, 0.52863333, 0.05194371]],

       [[0.10137847, 0.29719001, 0.8414199 ],
        [0.24385958, 0.47691064, 0.08908073]],

       [[0.26417179, 0.48012665, 0.60705232],
        [0.860328  , 0.54621554, 0.81900957]],

       [[0.13065812, 0.57814723, 0.75703656],
        [0.33013363, 0.87165546, 0.33758843]]])

In [15]:
np.random.randint(7,size=(2,3))

array([[6, 3, 2],
       [3, 3, 0]])

Repeat an array

In [24]:
b = np.array([[1,2,3]])
c = np.repeat(b,3,axis=0)
print(c)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z  #左闭右开
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays!!!

In [35]:
a = np.array([1,2,3])
b = a 
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [36]:
a = np.array([1,2,3])
b = a.copy()   #可以使用copy避免 
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


Linear Algebra

In [3]:
a = np.ones((2,4))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [15]:
alist = ["d","d","d",2,2,"d","d",4]

In [16]:
alist[0]

'd'

In [19]:
for i in alist:
    if i == "d":
        alist.remove(i)
        
print(alist)
    
    


[2, 2, 'd', 'd', 4]
